[build]
  command = "npm run build"
  ## The publish directory is handled automatically by the plugin.
  ## Do not manually set it to .next

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
